FROM node:18-alpine as build

WORKDIR /app

COPY package*.json ./
RUN npm install && \
    npm install terser --save-dev

COPY . .
RUN npm run build

FROM docker.io/nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"] 