version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - photos_data:/app/static/uploaded_photos
      - instance_data:/app/instance
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000

volumes:
  photos_data:
  instance_data: 